modLoader = "javafml"
loaderVersion = "[32,)"
license = "GNU GPLv3"
issueTrackerURL = "http://github.com/iCrazyBlaze/TwitchVsMinecraft2/issues"

[[mods]]
modId = "twitchmod"
version = "${version}"
displayName = "Twitch Vs Minecraft Reloaded"
updateJSONURL = "https://www.dropbox.com/s/qwmrqgdqe9jgnwf/tvm2-update.json?dl=0"
displayURL = "https://bit.ly/TwitchVsMinecraft"
logoFile = "logo.png"
credits = "Idea from Kaze Emanuar. Thanks to iGoodie, Commoble and MMD."
authors = "iCrazyBlaze"
description = '''
Be at your viewers' mercy! Random commands are chosen from the Twitch chat.
'''

[[dependencies.twitchmod]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"
