modLoader = "javafml"
loaderVersion = "[39,)"
license = "GNU LGPLv3"
issueTrackerURL = "http://github.com/iCrazyBlaze/TwitchVsMinecraft2/issues"

[[mods]]
modId = "twitchmod"
version = "${file.jarVersion}"
displayName = "Twitch Vs Minecraft Reloaded"
updateJSONURL = "https://raw.githubusercontent.com/iCrazyBlaze/TwitchVsMinecraft2/1.18/update.json"
displayURL = "https://bit.ly/TwitchVsMinecraft"
logoFile = "logo.png"
credits = "Idea from Kaze Emanuar. Thanks to the Minecraft Mod Development community for helping me create this!"
authors = "RonaRage (iCrazyBlaze/Btarg)"
description = "Be at your viewers' mercy! Random commands are chosen from Twitch chat or Discord."
itemIcon = "minecraft:anvil"

[[dependencies.twitchmod]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.twitchmod]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
side="BOTH"

[modproperties.configured]
catalogueImageIcon="icon.png"
configuredBackground="minecraft:textures/block/stone.png"