modLoader = "javafml"
loaderVersion = "[32,)"
license = "GNU LGPLv3"
issueTrackerURL = "http://github.com/iCrazyBlaze/TwitchVsMinecraft2/issues"

[[mods]]
modId = "twitchmod"
version = "${file.jarVersion}"
displayName = "Twitch Vs Minecraft Reloaded"
updateJSONURL = "https://raw.githubusercontent.com/iCrazyBlaze/TwitchVsMinecraft2/1.16/update.json"
displayURL = "https://bit.ly/TwitchVsMinecraft"
logoFile = "logo.png"
credits = "Idea from Kaze Emanuar. Thanks to iGoodie, Commoble and MMD."
authors = "iCrazyBlaze"
description = '''
Be at your viewers' mercy! Random commands are chosen from the Twitch chat.
'''

[[dependencies.twitchmod]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.twitchmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16,1.17)"
side="BOTH"
