---
version: "3"
services:
  app:
    build:
      #dockerfile: Dockerfile.ubuntu
      dockerfile: Dockerfile.alpine
      context: .
      args:  
        VARIANT: "3.15"
    ports: []
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspace:cached
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"

...