# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.224.2/containers/alpine/.devcontainer/base.Dockerfile

ARG VARIANT="3.15"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT}

RUN apk update \
    && apk upgrade \
    && apk add --no-cache openjdk17

RUN echo "export PATH='${PATH}:/usr/lib/jvm/default-jvm/jre/bin/'" >> /home/vscode/.bashrc ; \
    echo "alias ll='ls -al --color'" >> /home/vscode/.bashrc ;
